### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by pacocatech** [CR6Community/Marlin#321]
I'm trying to generate a version of your firmware, however, when running the build I'm getting this error message:
"
*** [.pio\build\STM32F103RET6_creality\src\src\module
\probe.cpp.o] Error 1

"

CR6-SE board 4.5.3

Another question, I'm trying to upload a version of marlin without updating my printer's display, however, every time I try to do that I can't install the current marlin on the machine, it freezes on the loading screen, you know what Can be?

**Comment by pacocatech** [comment]
My configuration and adv files:
[Marlin.zip](https://github.com/CR6Community/Marlin/files/9088364/Marlin.zip)

**Comment by pacocatech** [comment]
![image](https://user-images.githubusercontent.com/70729684/178380054-f428d9e0-792a-4bb3-a5b4-8b5deffbdd2e.png)
this is the situation when i try to put marlin 2.1.x on my cr6 itself, does anyone know why this happens?

**Comment by Thinkersbluff** [comment]
The Creality display is not programmed to work with Marlin 2.1, and Marlin 2.1 is not programmed to work with the Creality display. In that picture, you have the Creality firmware on the display. It is not going to load and run.

If you want to compile and load the Community Firmware onto your system, you must program both the display and the motherboard with the CF6.1 Community Firmware. They are a matched set. 

The pre-compiled 4.5.3 version is here: 
https://github.com/CR6Community/Marlin/releases/download/v2.0.8.1-cr6-community-release-6.1/CF6.1-Final-cr6-se-v4.5.3-mb-2021-06-04-16-53.zip

The Community Firmware source is on our GitHub page, along with the Release files, here:
https://github.com/CR6Community/Marlin/archive/refs/tags/v2.0.8.1-cr6-community-release-6.1.zip

**Comment by Thinkersbluff** [comment]
Disable the Probe tare buzzer line, to fix your compile error.

**i.e.: Do This:**
![image](https://user-images.githubusercontent.com/36551518/178385188-35a006b1-3945-4e37-acc0-5e624d299291.png)

**Comment by pacocatech** [comment]
Thanks, disabling that line made the build work.

Is there a version of marlin I can put that I don't have to mess with the display?
I just wanted to enable the m600 command on my CR6-SE

**Comment by Thinkersbluff** [comment]
None that I know of.
