### ISSUE TITLE
Community Firmware Compile Fails with Latest VSCode 1.74.3

### ISSUE THREAD

**Issue by ritchiedc** [CR6Community/Marlin#334]
### Did you test the latest `extui` code or prerelease?

Yes, and the problem still exists.

### Bug Description

The community firmware release 6.1 source code fails to compile with the latest VSCode v1.74.3. The static_assert lines in EstepsHandler.cpp and PIDHandler.cpp causes the compile to terminate. These appeared to be ignored in previous versions of VSCode. I completely removed VSCode and installed v1.60.0. The CFW code compiled without error. I then updated VSCode to the latest v1.74.3 from within VSCode. It now fails as follows

Marlin\src\lcd\extui\dgus_creality\creality_touch\EstepsHandler.cpp:47:47: error: static assertion failed: Assuming PURGE_LENGTH is 0 so we can use M701 

The compile will complete successfully by removing the static_assert line.

### Version of CR6Community Firmware

CF6.1

### Printer model

Creality CR-6 SE

### Motherboard

BigTreeTech SKR CR6

### Display

Creality CR-6 stock touch screen

### Mods

Direct drive

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by ghost** [comment]
Pull Request #347 submitted, proposing to patch the extui branch version of buildroot\share\PlatformIO\scripts\marlin.py\marlin.py per the verified fix we keep posting to the Discord:

replace:
    for define in env['CPPDEFINES']:

with:
    envdefs = env['CPPDEFINES'].copy()
    for define in envdefs:
